plugins:
  - babel
  - jest
env:
  node: true
  jest: true
parser: babel-eslint
extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - 'plugin:lodash-fp/recommended'
rules:
  no-console: 0
  import/no-unresolved: off
  import/extensions: off